version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/pages:/app/pages
      - ./frontend/public:/app/public
      - ./frontend/package.json:/app/package.json
      - ./frontend/package-lock.json:/app/package-lock.json
    environment:
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./backend/src:/usr/local/app/src
      - ./backend/package.json:/usr/local/app/package.json
      - ./backend/package-lock.json:/usr/local/app/package-lock.json
      - backend-node-modules:/usr/local/app/node_modules
    restart: always

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: players
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  backend-node-modules:
  mysql-data:
